# Generated by Django 6.0.3 on 2026-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('category', models.CharField(default='Food', max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
